# Numpy

In [1]:
! pip install numpy
import numpy as np


[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: C:\Users\Mati\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable


## Phase1

### Numpy array

In [2]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [3]:
another_arr_1d=np.array(['cat','dog','pig','hen'])
print(another_arr_1d)

['cat' 'dog' 'pig' 'hen']


In [4]:
boolean_array_1d=np.array(['true','false','false'])

In [5]:
test_arr=np.array([[1,2,4,5],[3,4,5,6]])
print(test_arr)

[[1 2 4 5]
 [3 4 5 6]]


In [6]:
print(test_arr)

[[1 2 4 5]
 [3 4 5 6]]


In [7]:
print(boolean_array_1d)

['true' 'false' 'false']


In [8]:
array_2d=np.array([[1,2,4,5],[6,8,9,1]])
print(array_2d)

[[1 2 4 5]
 [6 8 9 1]]


In [9]:
arr_2d = np.array([[1,2,3,4],[6,7,8,9]])

In [10]:
print(arr_2d)

[[1 2 3 4]
 [6 7 8 9]]


In [11]:
print(array_2d.ndim)

2


In [12]:
print(arr_2d.ndim)

2


In [13]:
print(arr_1d.ndim)

1


In [14]:
print(array_2d.shape)

(2, 4)


In [15]:
print(arr_2d.shape)

(2, 4)


In [16]:
empty_array_1_3=np.zeros((1,3))
print(empty_array_1_3)

[[0. 0. 0.]]


In [17]:
empty_array_3_4=np.zeros((3,4))
print(empty_array_3_4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
empty_arr=np.zeros((2,3))

In [19]:
print(empty_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
array_99 = np.ones((2,3))*99
print(array_99)

[[99. 99. 99.]
 [99. 99. 99.]]


In [21]:
array_one = np.ones((3,6))*7
print(array_one)

[[7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7.]]


In [22]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
test_numbers_odd=np.arange(1,100,2)
print(test_numbers_odd)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [24]:
divisible_by_3 = []
for n in test_numbers_odd:
    if n % 3 == 0:
        divisible_by_3.append(n)

In [25]:
for n in divisible_by_3:
    print(n)

3
9
15
21
27
33
39
45
51
57
63
69
75
81
87
93
99


In [26]:
print(np.random.randn(3))

[-0.94396694 -0.83042995 -0.7663831 ]


In [27]:
exam_scores = np.random.randint(50, 100, size=(5, 3))
print(exam_scores)


[[58 61 62]
 [61 82 69]
 [56 64 57]
 [64 80 69]
 [93 92 76]]


In [28]:
scores = np.array([88, 92, 75, 61, 95])
print(scores)

[88 92 75 61 95]


In [29]:
gradebook = np.array([
    [88, 75, 91],   # Ali:   Math, Sci, Eng
    [92, 89, 85],   # Sara:  Math, Sci, Eng
    [79, 91, 72],   # Bilal: Math, Sci, Eng
])
print(gradebook)


[[88 75 91]
 [92 89 85]
 [79 91 72]]


In [30]:
print(gradebook[1, 2])       

85


In [31]:
print(gradebook[0, :])   

[88 75 91]


In [32]:
print(gradebook[2, :])   

[79 91 72]


In [33]:
print(gradebook[:, 1])       

[75 89 91]


In [34]:
array_test=np.array([[1,2,4,5],[6,8,9,1]])

In [35]:
array_test

array([[1, 2, 4, 5],
       [6, 8, 9, 1]])

In [36]:
print(array_test[1,:])

[6 8 9 1]


In [37]:
print(array_test[:,1])

[2 8]


In [38]:
arr=np.arange(1,13)

In [39]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
arranged=arr.reshape(4,3)

In [41]:
arranged

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
ravelled=arranged.ravel()

In [43]:
print(ravelled)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [44]:
print(arranged.T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [45]:
scores = np.array([72, 85, 91, 68, 77])
curved = scores + 3

In [46]:
print(curved)

[75 88 94 71 80]


In [47]:
gradebook = np.array([         # shape (3, 3)
    [88, 75, 91],
    [92, 89, 85],
    [79, 91, 72],
])
bonus = np.array([5, 10, 3])

In [48]:

adjusted = gradebook + bonus   # broadcasts across all rows

# Column-wise operation using reshape
weights = np.array([0.4, 0.35, 0.25]).reshape(1, 3)
weighted = gradebook * weights


In [49]:
print(adjusted)

[[ 93  85  94]
 [ 97  99  88]
 [ 84 101  75]]


In [50]:
scores1 = np.array([88, 75, 91, 62, 95])

# # Math ufuncs — apply to every element
# print(np.sqrt(scores))         # sqrt of each
# print(np.log(scores))          # natural log
# print(np.abs(scores - 80))     # distance from 80

# # Trig
# angles = np.linspace(0, np.pi, 5)
# print(np.sin(angles).round(2))

# # Comparison ufuncs → boolean arrays
# print(np.greater(scores, 80))  # same as scores > 80

# # Two-array ufuncs
# midterm = np.array([80, 70, 88, 60, 90])


In [51]:
print(np.sqrt(adjusted))

[[ 9.64365076  9.21954446  9.69535971]
 [ 9.8488578   9.94987437  9.38083152]
 [ 9.16515139 10.04987562  8.66025404]]


In [52]:
print(np.square(adjusted))

[[ 8649  7225  8836]
 [ 9409  9801  7744]
 [ 7056 10201  5625]]


In [53]:
print(np.log(adjusted))

[[4.53259949 4.44265126 4.54329478]
 [4.57471098 4.59511985 4.47733681]
 [4.4308168  4.61512052 4.31748811]]


In [54]:
# gradebook: rows=students, cols=Math,Sci,Eng
gradebook = np.array([
    [88, 75, 91],
    [92, 89, 85],
    [79, 91, 72],
])

# Global aggregations (all elements)
print(np.sum(gradebook))       # 762
print(np.mean(gradebook))      # 84.67

# axis=0: aggregate across rows → per-subject stats
print(np.mean(gradebook, axis=0)) # [86.33 85. 82.67]

# axis=1: aggregate across cols → per-student stats
print(np.mean(gradebook, axis=1)) # [84.67 88.67 80.67]
print(np.std(gradebook,  axis=1)) # std per student


762
84.66666666666667
[86.33333333 85.         82.66666667]
[84.66666667 88.66666667 80.66666667]
[6.94422222 2.86744176 7.84573486]


In [55]:
scores2 = np.array([88, 72, 95, 61, 85, 79, 91])

# Boolean indexing — keep only scores above 80
mask   = scores2 > 80
top    = scores2[mask]          # [88 95 85 91]

# Compound condition
band   = scores2[(scores2>70) & (scores2<90)]  # [88 72 85 79]

# Assign to masked positions
scores2[scores2 < 70] = 70       # floor at 70

# Fancy indexing — arbitrary order, with repeats
pick = scores2[[0, 2, 0, 5]]   # indices 0,2,0,5
print(top)
print(pick)

# 2D fancy indexing
gradebook = np.array([[88,75,91],[92,89,85],[79,91,72]])
rows = np.array([0, 2])
print(gradebook[rows, :])      # rows 0 

[88 95 85 91]
[88 95 88 79]
[[88 75 91]
 [79 91 72]]


In [56]:
# Compound condition
band   = scores2[(scores2<70) & (scores2<90)]  # [88 72 85 79]

In [57]:
print(band)

[]


In [58]:
# Dot product (1D): sum of element-wise products
weights = np.array([0.4, 0.35, 0.25])  # exam weights
ali     = np.array([88, 75, 91])         # Ali's scores
final   = np.dot(weights, ali)           # weighted avg
print(f"Ali final: {final:.2f}")         # 83.45

# Matrix multiplication: gradebook × weights
gradebook = np.array([[88,75,91],[92,89,85],[79,91,72]])
finals    = gradebook @ weights          # or np.matmul()

# Inverse and determinant
A   = np.array([[2,1],[5,3]], dtype=float)
A_inv = np.linalg.inv(A)
print(np.linalg.det(A))

# Solve Ax = b (linear system)
b = np.array([1, 2])
x = np.linalg.solve(A, b)
print(x)


Ali final: 84.20
1.0000000000000009
[ 1. -1.]


In [59]:
term1 = np.array([[88,75,91],[92,89,85],[79,91,72]])
term2 = np.array([[85,80,88],[90,87,82],[83,94,76]])

In [60]:
term1

array([[88, 75, 91],
       [92, 89, 85],
       [79, 91, 72]])

In [61]:
term2

array([[85, 80, 88],
       [90, 87, 82],
       [83, 94, 76]])

In [62]:
all_terms=np.vstack((term1,term2))

In [63]:
all_terms

array([[88, 75, 91],
       [92, 89, 85],
       [79, 91, 72],
       [85, 80, 88],
       [90, 87, 82],
       [83, 94, 76]])

In [64]:
all_terms_horizontally=np.hstack((term1,term2))

In [65]:
all_terms_horizontally

array([[88, 75, 91, 85, 80, 88],
       [92, 89, 85, 90, 87, 82],
       [79, 91, 72, 83, 94, 76]])

In [66]:
print(all_terms_horizontally)

[[88 75 91 85 80 88]
 [92 89 85 90 87 82]
 [79 91 72 83 94 76]]


In [67]:
print(all_terms)

[[88 75 91]
 [92 89 85]
 [79 91 72]
 [85 80 88]
 [90 87 82]
 [83 94 76]]


In [73]:
# concatenate: general — specify axis
same_as_vstack = np.concatenate([term1, term2], axis=0)

# split: divide into equal chunks
a, b, c = np.split(all_terms, 3, axis=1)
print(a)
print(b)
print(c)


[[88]
 [92]
 [79]
 [85]
 [90]
 [83]]
[[75]
 [89]
 [91]
 [80]
 [87]
 [94]]
[[91]
 [85]
 [72]
 [88]
 [82]
 [76]]


In [77]:
np.save('horizontal.npzip',all_terms_horizontally)

In [ ]:
gradebook = np.array([[88, 75, 91], [92, 89, 85], [79, 91, 72]])
weights   = np.array([0.4, 0.35, 0.25])

# --- Save ---
# savetxt writes a text file and returns None -> don't assign it to a variable
# comments="" -> header line is written as "Math,Science,English" instead of
# "# Math,Science,English", so pandas.read_csv gets clean column names later
np.savetxt("gradebook.csv", gradebook,
           delimiter=",", fmt="%d",
           header="Math,Science,English", comments="")

# save the ARRAY itself, not the return value of savetxt
np.save("gradebook.npy", gradebook)

# savez puts several arrays into one .npz file (needed for the np.load below)
np.savez("semester.npz", gradebook=gradebook, weights=weights)

# --- Load back ---
loaded    = np.load("gradebook.npy")
multi     = np.load("semester.npz")
# header is now plain text (no '#'), so it must be skipped explicitly
from_csv  = np.loadtxt("gradebook.csv", delimiter=",", skiprows=1)

print(loaded)
print(multi["weights"])
print(from_csv)


In [83]:
import pandas as pd

df = pd.read_csv("gradebook.csv")
# columns: Math, Science, English (numeric)
print(df.columns.tolist())

['Math', 'Science', 'English']


In [84]:
# Extract raw NumPy array from DataFrame
arr = df[["Math","Science","English"]].to_numpy()

In [85]:
arr

array([[88, 75, 91],
       [92, 89, 85],
       [79, 91, 72]])

In [86]:
# Apply NumPy ops — then put back in pandas
df["weighted_avg"] = arr @ np.array([0.4, 0.35, 0.25])
df["z_score_math"] = (arr[:,0] - arr[:,0].mean()) / arr[:,0].std()


In [88]:
print(np.mean(arr))

84.66666666666667


In [87]:
# NumPy for fast custom aggregations
subject_corr = np.corrcoef(arr.T)   # 3×3 correlation


In [ ]:



# NumPy for fast custom aggregations
subject_corr = np.corrcoef(arr.T)   # 3×3 correlation

# Vectorized pandas column using np.where
df["grade"] = np.where(df["weighted_avg"] >= 90, "A",
             np.where(df["weighted_avg"] >= 75, "B", "C"))
print(df.head(3))


['Math', 'Science', 'English']
   Math  Science  English  weighted_avg  z_score_math grade
0    88       75       91         84.20      0.306570     B
1    92       89       85         89.20      1.042337     B
2    79       91       72         81.45     -1.348907     B
